# Generated by Django 4.2.7 on 2024-11-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("url", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "group",
            },
        ),
        migrations.CreateModel(
            name="SavedApiCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_method", models.CharField(max_length=10)),
                ("api_path", models.CharField(max_length=500)),
                ("directory", models.CharField(max_length=100)),
                ("bussiness_code", models.TextField(blank=True, null=True)),
                ("common_code", models.TextField(blank=True, null=True)),
                ("testcases_code", models.TextField(blank=True, null=True)),
                ("is_auto_test", models.BooleanField(default=False)),
                ("report_url", models.CharField(blank=True, max_length=500, null=True)),
                ("header_params", models.TextField(blank=True, null=True)),
                ("path_params", models.TextField(blank=True, null=True)),
                ("query_params", models.TextField(blank=True, null=True)),
                ("body_params", models.TextField(blank=True, null=True)),
                ("response_params", models.TextField(blank=True, null=True)),
                ("group", models.TextField(default="[]")),
                ("apiinfo", models.JSONField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("api_method", "api_path", "directory")},
            },
        ),
    ]
