# Generated by Django 4.2.7 on 2024-11-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SavedAPIDirectory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("directory_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Saved API Directories",
            },
        ),
        migrations.CreateModel(
            name="SavedAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apiinfo", models.JSONField()),
                ("directory", models.CharField(max_length=255)),
                ("api_method", models.CharField(max_length=10)),
                ("api_path", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "savedapis",
                "indexes": [
                    models.Index(
                        fields=["directory", "api_method", "api_path"],
                        name="savedapis_directo_3d139d_idx",
                    )
                ],
                "unique_together": {("directory", "api_method", "api_path")},
            },
        ),
    ]
