# Generated by Django 4.2.7 on 2024-11-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FunctionCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("module", models.CharField(max_length=255)),
                ("testtitle", models.CharField(max_length=255)),
                ("directory", models.CharField(max_length=255)),
                ("importance", models.CharField(max_length=50)),
                ("precondition", models.TextField()),
                ("testinput", models.TextField()),
                ("steps", models.TextField()),
                ("expectedresults", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "function_cases",
                "ordering": ["-created_at"],
            },
        ),
    ]
